# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191111_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='new book'),
            preserve_default=False,
        ),
    ]
